"""new ticket table

Revision ID: 908afdb04878
Revises: 
Create Date: 2020-10-27 13:32:35.098762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908afdb04878'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester', sa.String(length=64), nullable=True),
    sa.Column('request', sa.String(length=160), nullable=True),
    sa.Column('urgency', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_request'), 'ticket', ['request'], unique=True)
    op.create_index(op.f('ix_ticket_requester'), 'ticket', ['requester'], unique=False)
    op.create_index(op.f('ix_ticket_urgency'), 'ticket', ['urgency'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_urgency'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_requester'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_request'), table_name='ticket')
    op.drop_table('ticket')
    # ### end Alembic commands ###
